name = "capp"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.17"
build_base_image = "golang:1.17"
enable_go_build_cache = true

[builders."docker:generic"]
enabled = true
build_base_image = "golang:1.17"
go_version = "1.17"
enable_go_build_cache = true

[builders."docker:generic".build_args]
GO_PROXY = "https://proxy.golang.org"

[builders."exec:go"]
enabled = true
go_version = "1.17"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "cel-app"
instances = { min = 1, max = 2, default = 1 }